@ECHO OFF

REM
REM This script uses the full path to your DRG Mods directory.
REM You can customize this using the env var "DRG_MODS".
REM

IF "%DRG_MODS%" == "" (
   SET "DRG_MODS=C:\Games\Steam\steamapps\common\Deep Rock Galactic\FSD\Mods"
)

REM Generated by UE's "Package Product" operation
ECHO.
ECHO --- Cleaning "WindowsNoEditor" package directory...
RMDIR /S /Q WindowsNoEditor

REM Generated by our "stage" script
ECHO.
ECHO --- Cleaning "input" directory...
RMDIR /S /Q input

REM Generated by our "pack" script running UnrealPak
ECHO.
ECHO --- Cleaning "pak" directory...
RMDIR /S /Q RigHUD

REM Generated by our "install" script
ECHO.
ECHO --- Cleaning "Mods" directory (removes all manually installed mods)...
RMDIR /S /Q "%DRG_MODS%\RigHUD"

ECHO.
PAUSE
